"""empty message

Revision ID: 9f80828a944d
Revises: 
Create Date: 2023-04-18 11:38:46.445595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f80828a944d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streak',
    sa.Column('userid', sa.Integer(), nullable=False, foriegn_key=True),
    sa.Column('habitid', sa.Integer(), nullable=False, foriegn_key=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('userid', 'habitid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('streak')
    # ### end Alembic commands ###
